# MyBatis 설정
mybatis:
   mapper-locations: classpath:/sqlmap/sqlmapper_*.xml
   # 내가 VO를 작성한 위치
   type-aliases-package: com.example.first_spring.vo
   
# MySQL 접속정보 설정
# tab은 계층 표현이기 때문에 꼭 써줘야함
spring:
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/dw?useUnicode=true&charaterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: 5191
      